# Generated by Django 4.2.5 on 2023-09-24 09:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Family1399",
            fields=[
                (
                    "ParentID",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "MembersID",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Family1400",
            fields=[
                (
                    "ParentID",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "MembersID",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
