# Generated by Django 4.2.5 on 2023-09-24 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_alter_family1399_membersid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SameFamilies",
            fields=[
                (
                    "ParentID",
                    models.PositiveBigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "MembersID",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveBigIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("parentid_1399", models.PositiveBigIntegerField()),
                ("parentid_1400", models.PositiveBigIntegerField()),
                (
                    "membersid_1399",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveBigIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "membersid_1400",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveBigIntegerField(),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SamePeople",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_1399", models.PositiveBigIntegerField()),
                ("id_1400", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Family1399",
        ),
        migrations.DeleteModel(
            name="Family1400",
        ),
        migrations.DeleteModel(
            name="People1399",
        ),
        migrations.DeleteModel(
            name="People1400",
        ),
    ]
